In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [2]:
df = pd.read_csv('/Users/fahad/GP-ML/Data/loan-train.csv')

In [3]:
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [5]:
df.describe()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,614.000000,614.000000,592.000000,600.00000,564.000000
mean,5403.459283,1621.245798,146.412162,342.00000,0.842199
std,6109.041673,2926.248369,85.587325,65.12041,0.364878
min,150.000000,0.000000,9.000000,12.00000,0.000000
25%,2877.500000,0.000000,100.000000,360.00000,1.000000
50%,3812.500000,1188.500000,128.000000,360.00000,1.000000
75%,5795.000000,2297.250000,168.000000,360.00000,1.000000
max,81000.000000,41667.000000,700.000000,480.00000,1.000000

In [6]:
df.shape

(614, 13)

In [11]:
df = df.fillna(df.mean(numeric_only=True))

In [12]:
df.Gender = df.Gender.replace({"Male": 1, "Female" : 0})
df.Married = df.Married.replace({"Yes": 1, "No" : 0})
df.Loan_Status = df.Loan_Status.replace({"Y": 1, "N" : 0})
df.Self_Employed = df.Self_Employed.replace({"Yes": 1, "No" : 0})

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             614 non-null    float64
 2   Married            614 non-null    float64
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      614 non-null    float64
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         614 non-null    float64
 9   Loan_Amount_Term   614 non-null    float64
 10  Credit_History     614 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    int64
dtypes: float64(7), int64(2), object(4)
memory usage: 62.5+ KB

In [14]:
df['Gender'] = df['Gender'].astype(int)
df['Married'] = df['Married'].astype(int)
df['Self_Employed'] = df['Self_Employed'].astype(int)
df['Self_Employed'] = df['Self_Employed'].astype(int)
df['ApplicantIncome'] = df['ApplicantIncome'].astype(float)
df['Credit_History'] = df['Credit_History'].astype(int)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             614 non-null    int32
 2   Married            614 non-null    int32
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      614 non-null    int32
 6   ApplicantIncome    614 non-null    float64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         614 non-null    float64
 9   Loan_Amount_Term   614 non-null    float64
 10  Credit_History     614 non-null    int32
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    int64
dtypes: float64(4), int32(4), int64(1), object(4)
memory usage: 52.9+ KB

In [32]:
features  = df.drop(['Loan_ID','LoanAmount','Dependents','Property_Area','Education','Loan_Amount_Term','Loan_Status'], axis=1).values
features

array([[1.000e+00, 0.000e+00, 0.000e+00, 5.849e+03, 0.000e+00, 1.000e+00],
       [1.000e+00, 1.000e+00, 0.000e+00, 4.583e+03, 1.508e+03, 1.000e+00],
       [1.000e+00, 1.000e+00, 1.000e+00, 3.000e+03, 0.000e+00, 1.000e+00],
       ...,
       [1.000e+00, 1.000e+00, 0.000e+00, 8.072e+03, 2.400e+02, 1.000e+00],
       [1.000e+00, 1.000e+00, 0.000e+00, 7.583e+03, 0.000e+00, 1.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 4.583e+03, 0.000e+00, 0.000e+00]])

In [33]:
target = df['LoanAmount'].values
target.reshape(-1,1)

array([[146.41216216],
       [128.        ],
       [ 66.        ],
       [120.        ],
       [141.        ],
       [267.        ],
       [ 95.        ],
       [158.        ],
       [168.        ],
       [349.        ],
       [ 70.        ],
       [109.        ],
       [200.        ],
       [114.        ],
       [ 17.        ],
       [125.        ],
       [100.        ],
       [ 76.        ],
       [133.        ],
       [115.        ],
       [104.        ],
       [315.        ],
       [116.        ],
       [112.        ],
       [151.        ],
       [191.        ],
       [122.        ],
       [110.        ],
       [ 35.        ],
       [120.        ],
       [201.        ],
       [ 74.        ],
       [106.        ],
       [114.        ],
       [320.        ],
       [146.41216216],
       [100.        ],
       [144.        ],
       [184.        ],
       [110.        ],
       [ 80.        ],
       [ 47.        ],
       [ 75.        ],
       [134.        ],
       [ 96.        ],
       [ 88.        ],
       [ 44.        ],
       [144.        ],
       [120.        ],
       [144.        ],
       [100.        ],
       [120.        ],
       [112.        ],
       [134.        ],
       [286.        ],
       [ 97.        ],
       [ 96.        ],
       [135.        ],
       [180.        ],
       [144.        ],
       [120.        ],
       [ 99.        ],
       [165.        ],
       [146.41216216],
       [116.        ],
       [258.        ],
       [126.        ],
       [312.        ],
       [125.        ],
       [136.        ],
       [172.        ],
       [ 97.        ],
       [ 81.        ],
       [ 95.        ],
       [187.        ],
       [113.        ],
       [176.        ],
       [110.        ],
       [180.        ],
       [130.        ],
       [111.        ],
       [146.41216216],
       [167.        ],
       [265.        ],
       [ 50.        ],
       [136.        ],
       [ 99.        ],
       [104.        ],
       [210.        ],
       [175.        ],
       [131.        ],
       [188.        ],
       [ 81.        ],
       [122.        ],
       [ 25.        ],
       [146.41216216],
       [137.        ],
       [ 50.        ],
       [115.        ],
       [131.        ],
       [133.        ],
       [151.        ],
       [146.41216216],
       [146.41216216],
       [160.        ],
       [100.        ],
       [225.        ],
       [120.        ],
       [216.        ],
       [ 94.        ],
       [136.        ],
       [139.        ],
       [152.        ],
       [146.41216216],
       [118.        ],
       [185.        ],
       [154.        ],
       [ 85.        ],
       [175.        ],
       [259.        ],
       [180.        ],
       [ 44.        ],
       [137.        ],
       [ 81.        ],
       [194.        ],
       [ 93.        ],
       [370.        ],
       [146.41216216],
       [160.        ],
       [182.        ],
       [650.        ],
       [ 74.        ],
       [ 70.        ],
       [ 25.        ],
       [102.        ],
       [290.        ],
       [ 84.        ],
       [ 88.        ],
       [242.        ],
       [129.        ],
       [185.        ],
       [168.        ],
       [175.        ],
       [122.        ],
       [187.        ],
       [100.        ],
       [ 70.        ],
       [ 30.        ],
       [225.        ],
       [125.        ],
       [118.        ],
       [152.        ],
       [244.        ],
       [113.        ],
       [ 50.        ],
       [600.        ],
       [160.        ],
       [187.        ],
       [120.        ],
       [255.        ],
       [ 98.        ],
       [275.        ],
       [121.        ],
       [158.        ],
       [ 75.        ],
       [182.        ],
       [112.        ],
       [129.        ],
       [ 63.        ],
       [200.        ],
       [ 95.        ],
       [700.        ],
       [ 81.        ],
       [187.        ],
       [ 87.        ],
       [116.        ],
       [101.        ],
       [495.        ],
       [116.        ],
       [102.        ],
       [180.        ],
       [ 67.        ],
       [ 73.        ],
       [260.        ],
       [108.        ],
       [120.        ],
       [ 66.        ],
       [ 58.        ],
       [168.        ],
       [188.        ],
       [ 48.        ],
       [164.        ],
       [160.        ],
       [ 76.        ],
       [120.        ],
       [170.        ],
       [187.        ],
       [120.        ],
       [113.        ],
       [ 83.        ],
       [ 90.        ],
       [166.        ],
       [146.41216216],
       [135.        ],
       [124.        ],
       [120.        ],
       [ 80.        ],
       [ 55.        ],
       [ 59.        ],
       [127.        ],
       [214.        ],
       [128.        ],
       [240.        ],
       [130.        ],
       [137.        ],
       [100.        ],
       [135.        ],
       [131.        ],
       [ 72.        ],
       [127.        ],
       [ 60.        ],
       [116.        ],
       [144.        ],
       [175.        ],
       [128.        ],
       [170.        ],
       [138.        ],
       [210.        ],
       [158.        ],
       [200.        ],
       [104.        ],
       [ 42.        ],
       [120.        ],
       [280.        ],
       [140.        ],
       [170.        ],
       [255.        ],
       [122.        ],
       [112.        ],
       [ 96.        ],
       [120.        ],
       [140.        ],
       [155.        ],
       [108.        ],
       [123.        ],
       [120.        ],
       [112.        ],
       [137.        ],
       [123.        ],
       [ 90.        ],
       [201.        ],
       [138.        ],
       [104.        ],
       [279.        ],
       [192.        ],
       [255.        ],
       [115.        ],
       [ 94.        ],
       [304.        ],
       [128.        ],
       [330.        ],
       [134.        ],
       [155.        ],
       [120.        ],
       [128.        ],
       [151.        ],
       [150.        ],
       [160.        ],
       [135.        ],
       [ 90.        ],
       [ 30.        ],
       [136.        ],
       [126.        ],
       [150.        ],
       [ 90.        ],
       [115.        ],
       [207.        ],
       [ 80.        ],
       [436.        ],
       [124.        ],
       [158.        ],
       [112.        ],
       [ 78.        ],
       [ 54.        ],
       [146.41216216],
       [ 89.        ],
       [ 99.        ],
       [120.        ],
       [115.        ],
       [187.        ],
       [139.        ],
       [127.        ],
       [134.        ],
       [143.        ],
       [172.        ],
       [110.        ],
       [200.        ],
       [135.        ],
       [151.        ],
       [113.        ],
       [ 93.        ],
       [105.        ],
       [132.        ],
       [ 96.        ],
       [140.        ],
       [146.41216216],
       [135.        ],
       [104.        ],
       [480.        ],
       [185.        ],
       [ 84.        ],
       [111.        ],
       [ 56.        ],
       [144.        ],
       [159.        ],
       [111.        ],
       [120.        ],
       [ 88.        ],
       [112.        ],
       [155.        ],
       [115.        ],
       [124.        ],
       [146.41216216],
       [132.        ],
       [300.        ],
       [376.        ],
       [130.        ],
       [184.        ],
       [110.        ],
       [ 67.        ],
       [117.        ],
       [ 98.        ],
       [ 71.        ],
       [490.        ],
       [182.        ],
       [ 70.        ],
       [160.        ],
       [176.        ],
       [146.41216216],
       [ 71.        ],
       [173.        ],
       [ 46.        ],
       [158.        ],
       [ 74.        ],
       [125.        ],
       [160.        ],
       [152.        ],
       [126.        ],
       [259.        ],
       [187.        ],
       [228.        ],
       [308.        ],
       [ 95.        ],
       [105.        ],
       [130.        ],
       [116.        ],
       [165.        ],
       [ 67.        ],
       [100.        ],
       [200.        ],
       [ 81.        ],
       [236.        ],
       [130.        ],
       [ 95.        ],
       [141.        ],
       [133.        ],
       [ 96.        ],
       [124.        ],
       [175.        ],
       [570.        ],
       [ 55.        ],
       [155.        ],
       [380.        ],
       [111.        ],
       [110.        ],
       [120.        ],
       [130.        ],
       [130.        ],
       [ 71.        ],
       [130.        ],
       [128.        ],
       [296.        ],
       [156.        ],
       [128.        ],
       [100.        ],
       [113.        ],
       [132.        ],
       [146.41216216],
       [136.        ],
       [125.        ],
       [185.        ],
       [275.        ],
       [120.        ],
       [113.        ],
       [113.        ],
       [135.        ],
       [ 71.        ],
       [ 95.        ],
       [109.        ],
       [103.        ],
       [ 45.        ],
       [ 65.        ],
       [103.        ],
       [ 53.        ],
       [194.        ],
       [115.        ],
       [115.        ],
       [ 66.        ],
       [152.        ],
       [360.        ],
       [ 62.        ],
       [160.        ],
       [218.        ],
       [110.        ],
       [178.        ],
       [ 60.        ],
       [160.        ],
       [239.        ],
       [112.        ],
       [138.        ],
       [138.        ],
       [ 80.        ],
       [100.        ],
       [110.        ],
       [ 96.        ],
       [121.        ],
       [ 81.        ],
       [133.        ],
       [ 87.        ],
       [ 60.        ],
       [150.        ],
       [105.        ],
       [405.        ],
       [143.        ],
       [100.        ],
       [146.41216216],
       [ 50.        ],
       [146.41216216],
       [187.        ],
       [138.        ],
       [187.        ],
       [180.        ],
       [148.        ],
       [152.        ],
       [175.        ],
       [130.        ],
       [110.        ],
       [ 55.        ],
       [150.        ],
       [190.        ],
       [125.        ],
       [ 60.        ],
       [149.        ],
       [ 90.        ],
       [ 84.        ],
       [ 96.        ],
       [118.        ],
       [173.        ],
       [136.        ],
       [160.        ],
       [160.        ],
       [128.        ],
       [153.        ],
       [132.        ],
       [ 98.        ],
       [140.        ],
       [ 70.        ],
       [110.        ],
       [ 98.        ],
       [110.        ],
       [162.        ],
       [113.        ],
       [100.        ],
       [ 93.        ],
       [162.        ],
       [150.        ],
       [230.        ],
       [132.        ],
       [ 86.        ],
       [146.41216216],
       [154.        ],
       [113.        ],
       [128.        ],
       [234.        ],
       [246.        ],
       [131.        ],
       [ 80.        ],
       [500.        ],
       [160.        ],
       [ 75.        ],
       [ 96.        ],
       [186.        ],
       [110.        ],
       [225.        ],
       [119.        ],
       [105.        ],
       [107.        ],
       [111.        ],
       [ 95.        ],
       [209.        ],
       [113.        ],
       [100.        ],
       [208.        ],
       [138.        ],
       [124.        ],
       [243.        ],
       [480.        ],
       [ 96.        ],
       [188.        ],
       [ 40.        ],
       [100.        ],
       [250.        ],
       [148.        ],
       [ 70.        ],
       [311.        ],
       [150.        ],
       [113.        ],
       [123.        ],
       [185.        ],
       [ 95.        ],
       [ 45.        ],
       [ 55.        ],
       [100.        ],
       [480.        ],
       [146.41216216],
       [400.        ],
       [110.        ],
       [161.        ],
       [ 94.        ],
       [130.        ],
       [216.        ],
       [100.        ],
       [110.        ],
       [196.        ],
       [125.        ],
       [126.        ],
       [324.        ],
       [107.        ],
       [ 66.        ],
       [157.        ],
       [140.        ],
       [ 99.        ],
       [ 95.        ],
       [128.        ],
       [102.        ],
       [155.        ],
       [ 80.        ],
       [145.        ],
       [103.        ],
       [110.        ],
       [146.41216216],
       [146.41216216],
       [158.        ],
       [181.        ],
       [132.        ],
       [ 26.        ],
       [ 84.        ],
       [260.        ],
       [162.        ],
       [182.        ],
       [108.        ],
       [600.        ],
       [211.        ],
       [132.        ],
       [258.        ],
       [120.        ],
       [ 70.        ],
       [123.        ],
       [  9.        ],
       [104.        ],
       [186.        ],
       [165.        ],
       [275.        ],
       [187.        ],
       [150.        ],
       [108.        ],
       [136.        ],
       [110.        ],
       [107.        ],
       [161.        ],
       [205.        ],
       [ 90.        ],
       [ 36.        ],
       [ 61.        ],
       [146.        ],
       [172.        ],
       [104.        ],
       [ 70.        ],
       [ 94.        ],
       [106.        ],
       [ 56.        ],
       [205.        ],
       [292.        ],
       [142.        ],
       [260.        ],
       [110.        ],
       [187.        ],
       [ 88.        ],
       [180.        ],
       [192.        ],
       [350.        ],
       [155.        ],
       [128.        ],
       [172.        ],
       [496.        ],
       [146.41216216],
       [173.        ],
       [157.        ],
       [108.        ],
       [ 71.        ],
       [ 40.        ],
       [253.        ],
       [187.        ],
       [133.        ]])

In [34]:
from sklearn.model_selection import train_test_split

In [35]:
x_train,x_test,y_train,y_test = train_test_split(features,target,test_size=0.3,random_state=0)

In [36]:
x_train.shape,y_train.shape

((429, 6), (429,))

In [37]:
from sklearn.preprocessing import StandardScaler

In [38]:
scaler = StandardScaler()
x_train[3:5] = scaler.fit_transform(x_train[3:5])
x_test[3:5] = scaler.transform(x_test[3:5])

In [39]:
x_train,x_test

(array([[1.000e+00, 0.000e+00, 0.000e+00, 8.750e+03, 4.167e+03, 1.000e+00],
        [1.000e+00, 1.000e+00, 0.000e+00, 3.859e+03, 3.300e+03, 1.000e+00],
        [1.000e+00, 1.000e+00, 0.000e+00, 2.400e+03, 2.167e+03, 1.000e+00],
        ...,
        [1.000e+00, 1.000e+00, 0.000e+00, 5.167e+03, 3.167e+03, 1.000e+00],
        [1.000e+00, 1.000e+00, 0.000e+00, 6.033e+03, 0.000e+00, 1.000e+00],
        [0.000e+00, 1.000e+00, 0.000e+00, 4.180e+03, 2.306e+03, 1.000e+00]]),
 array([[1.000e+00, 0.000e+00, 1.000e+00, 7.085e+03, 0.000e+00, 1.000e+00],
        [0.000e+00, 0.000e+00, 0.000e+00, 4.230e+03, 0.000e+00, 1.000e+00],
        [1.000e+00, 1.000e+00, 0.000e+00, 6.133e+03, 3.906e+03, 1.000e+00],
        ...,
        [0.000e+00, 1.000e+00, 0.000e+00, 3.166e+03, 0.000e+00, 1.000e+00],
        [1.000e+00, 1.000e+00, 0.000e+00, 3.250e+03, 0.000e+00, 1.000e+00],
        [1.000e+00, 0.000e+00, 0.000e+00, 4.895e+03, 0.000e+00, 1.000e+00]]))

In [40]:
from sklearn.ensemble import RandomForestRegressor

In [41]:
ml_model = RandomForestRegressor()

In [42]:
ml_model.fit(x_train, y_train)

RandomForestRegressor()

In [43]:
y_pred = ml_model.predict(x_test)
y_pred

array([130.28236486,  93.97      , 269.39      , 122.98      ,
       148.42060811, 107.82060811, 162.03      , 180.88      ,
       127.61472973, 116.59885135,  90.93      ,  78.87533784,
       179.90304054, 179.96824324, 233.61      ,  95.37      ,
       108.72236486, 111.93060811,  94.36891892, 133.04891892,
       103.38297297, 133.71540541, 169.58236486, 238.38      ,
       117.11533784, 213.05      , 166.36      , 252.35      ,
       120.4       , 118.20885135, 190.21      , 137.59      ,
       139.65236486, 234.21      , 157.62121622, 111.53297297,
       122.70006757, 121.99648649, 171.48333333,  83.1       ,
        54.3       , 150.44      ,  54.64060811, 105.16078829,
       102.13      , 255.14412162, 103.4       ,  93.17866667,
       138.74824324, 121.85885135,  87.34      , 159.12418919,
       125.60060811, 116.82060811, 122.41      , 223.26      ,
       120.44121622, 133.9385    , 127.3477027 , 110.27      ,
       187.7       , 182.12959459, 115.41648649, 115.87      ,
       166.625     , 262.98      , 123.89885135, 120.46236486,
       153.66824324, 120.55824324, 127.56472973,  74.87412162,
        87.34824324, 185.21709459, 122.42891892, 133.90540541,
       215.45      , 210.19      , 225.46      ,  78.23      ,
       135.24824324, 346.03709459, 138.8372973 , 150.64236486,
       171.62      , 149.42182432, 132.63412162, 243.08      ,
        63.1       , 123.97304054, 106.29648649,  86.49      ,
       151.94      , 134.78533784,  86.15      , 124.27      ,
       138.20394144, 120.28824324, 128.64      , 223.58      ,
       219.66      ,  83.92412162, 278.55      , 301.91745495,
       155.26      , 146.17182432, 121.55      , 116.37      ,
       109.15472973,  79.76      , 132.00903153, 125.83      ,
        98.6       ,  95.31      , 125.41945946, 143.32716216,
       115.79885135, 104.30412162, 138.65297297, 303.4       ,
       216.86      , 133.37128378, 102.67      , 142.01885135,
       204.65      , 118.19412162, 111.38      , 106.98412162,
       186.21      , 226.02      ,  97.85898649, 162.77412162,
        60.17412162,  55.49412162, 108.67      ,  87.98      ,
       145.55128378,  94.5       ,  64.92      ,  84.68      ,
        81.82333333, 211.6       , 130.37891892, 150.33533784,
       155.18243243, 435.88128378, 142.6947973 , 358.41297297,
        92.77      , 112.51236486, 251.        , 231.51      ,
       149.55162162, 114.72      , 149.05      , 116.96      ,
       241.68      , 135.76047297,  87.28648649, 131.50243243,
       114.98      ,  97.3       , 143.13183333,  69.56      ,
       109.46412162,  89.8       , 217.03      ,  76.74709459,
       140.41      , 180.26      , 101.11333333, 208.41297297,
       141.32297297,  93.94412162, 157.27236486,  68.1       ,
       110.21      , 144.95      , 200.46885135,  66.23      ,
       175.01      , 134.28      ,  94.96      ,  69.52      ,
       137.64      ])

In [44]:
from sklearn.metrics import accuracy_score
score = ml_model.score(x_train, y_train)
print('accuracy_score overall :', score)
print('accuracy_score percent :', round(score*100,2))

accuracy_score overall : 0.9222236215930949
accuracy_score percent : 92.22

In [46]:
ml_model.predict([[0,0,0,5849,0.0,1]])

array([140.08880631])

In [47]:
import pickle as pkl

In [48]:
filename = 'loan_amount_model.pkl'
pkl.dump(ml_model, open(filename, 'wb'))